import ToolErrorBoundary from './ToolErrorBoundary';
import { useMemo, useState } from 'react';
import { Download, FileUp, RotateCcw } from 'lucide-react';
import { parseCSV } from '../lib/csv';
import { fixCSVDateColumn, convertDate } from '../lib/dates';
import type { DateFormat, DateOutput } from '../lib/dates';
import { downloadText } from '../lib/download';
const sample = 'customer,date,amount\nAsha,31/12/2025,120\nRavi,29/02/2024,450\nMeera,31/02/2025,300\nNitin,03/04/2026,900';
export default function DatesTool() {return <ToolErrorBoundary><DatesToolImpl /></ToolErrorBoundary>}
function DatesToolImpl() {
  const [text, setText] = useState(''); const [column, setColumn] = useState(1);
  const [inputFormat, setInputFormat] = useState<DateFormat>('AUTO'); const [outputFormat, setOutputFormat] = useState<DateOutput>('ISO');
  const [delimiter, setDelimiter] = useState(','); const [fileError, setFileError] = useState('');
  const parsed = useMemo(() => { try {return { rows: parseCSV(text, delimiter), error: ''};} catch(e) {return {rows: [] as string[][], error: (e as Error).message};} }, [text, delimiter]);
  const headers = parsed.rows[0] ?? [];
  const selectedColumn = Math.min(column, Math.max(0, headers.length-1));
  const result = useMemo(()=> {if(!text.trim() || parsed.error) return null;try {return fixCSVDateColumn(text, selectedColumn, inputFormat, outputFormat, delimiter);}catch {return null;}},[text,parsed.error,selectedColumn,inputFormat,outputFormat,delimiter]);
  async function upload(file?: File) { if(!file)return; setFileError(''); if(file.size>3*1024*1024){setFileError('File exceeds the 3 MB browser preview limit.');return;}try{const content=await file.text();setText(content);setColumn(1);}catch {setFileError('Unable to read this file.');} }
  return <><div className="app-intro"><h2>Fix dates without guesswork</h2><p>Auto mode fixes only unambiguous dates, even in mixed-format files. Choose an explicit source format when you know it; unresolved values remain untouched.</p></div>
    <div className="app-grid"><section className="panel"><div className="panel-header"><h3>01 / Import your data</h3><span className="panel-hint">CSV or TSV</span></div><div className="field"><label htmlFor="csv-upload">Upload CSV or TSV</label><div className="upload-box"><FileUp size={19} style={{display:'block',margin:'0 auto 10px'}}/><input id="csv-upload" type="file" accept=".csv,.tsv,text/csv,text/tab-separated-values,text/plain" onChange={e=>void upload(e.target.files?.[0])}/></div></div><div className="field"><label htmlFor="csv-text">Or paste spreadsheet data</label><textarea id="csv-text" value={text} onChange={e=>setText(e.target.value)} placeholder={'customer,date,amount\nAsha,31/12/2025,120'} /></div><div className="action-row"><button className="btn ghost" type="button" onClick={()=>{setText(sample);setColumn(1);setDelimiter(',');setFileError('');}}>Load sample</button><button className="btn ghost" type="button" onClick={()=>{setText('');setFileError('');}} disabled={!text}><RotateCcw size={14}/> Clear</button></div>{(fileError||parsed.error) && <p className="notice error" role="alert">{fileError||parsed.error}</p>}</section>
      <section className="panel"><div className="panel-header"><h3>02 / Conversion rules</h3><span className="panel-hint">Preview first</span></div><div className="field-row"><div className="field"><label htmlFor="csv-delimiter">CSV delimiter</label><select id="csv-delimiter" value={delimiter} onChange={e=>{setDelimiter(e.target.value);setColumn(0);}}><option value=",">Comma</option><option value=";">Semicolon</option><option value={'\t'}>Tab</option></select></div><div className="field"><label htmlFor="csv-column">Date column</label><select id="csv-column" value={selectedColumn} onChange={e=>setColumn(Number(e.target.value))} disabled={!headers.length}>{headers.length ? headers.map((h,i)=><option value={i} key={i}>{h||`Column ${i+1}`}</option>) : <option value={0}>Upload data first</option>}</select></div></div><div className="field-row"><div className="field"><label htmlFor="source-date-format">Original format</label><select id="source-date-format" value={inputFormat} onChange={e=>setInputFormat(e.target.value as DateFormat)}><option value="AUTO">Auto (unambiguous only)</option><option value="DMY">DD/MM/YYYY</option><option value="MDY">MM/DD/YYYY</option><option value="YMD">YYYY-MM-DD</option></select></div><div className="field"><label htmlFor="target-date-format">Convert to</label><select id="target-date-format" value={outputFormat} onChange={e=>setOutputFormat(e.target.value as DateOutput)}><option value="ISO">YYYY-MM-DD (ISO)</option><option value="DMY">DD/MM/YYYY</option><option value="MDY">MM/DD/YYYY</option></select></div></div>
      {result ? <><div className="stats-line"><span><b>{result.fixed}</b> converted</span><span><b>{result.invalid}</b> invalid</span><span><b>{result.ambiguous}</b> ambiguous</span><span><b>{result.unchanged}</b> unchanged</span></div><div className="data-table-wrap"><table className="data-table"><thead><tr>{result.headers.map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{result.rows.slice(0,20).map((row,i)=><tr key={i} className={(parsed.rows[i+1]?.[selectedColumn]??'').trim() && convertDate(parsed.rows[i+1]?.[selectedColumn]??'', inputFormat, outputFormat)===null ? 'invalid' : ''}>{result.headers.map((_,j)=><td key={j}>{row[j]??''}</td>)}</tr>)}</tbody></table></div>{result.invalid + result.ambiguous > 0 && <div className="notice warn" role="status">{result.invalid} invalid and {result.ambiguous} ambiguous dates were left unchanged. Choose a specific input format if you know which date convention applies, and review before importing.</div>}<p className="muted">Preview shows the first 20 data rows.</p><div className="action-row"><button className="btn primary" type="button" onClick={()=>downloadText(result.csv,'aetherexa-fixed-dates.csv')}><Download size={15}/> Download corrected CSV</button></div></> : <div className="image-result-wrap"><p>Upload a CSV or load the sample to configure conversion and see results.</p></div>}
      </section></div></>;
}
