import ToolErrorBoundary from './ToolErrorBoundary';
import { useMemo, useState } from 'react';
import { Download, Printer } from 'lucide-react';
import { parsePriceList } from '../lib/prices';
import { downloadText } from '../lib/download';
const sample = 'Rice,65,kg\nWheat Flour,42,kg\nSugar,48,kg\nToor Dal,155,kg\nBath Soap,35,each\nSunflower Oil,145,litre';
export default function PriceTool() {return <ToolErrorBoundary><PriceToolImpl /></ToolErrorBoundary>}
function PriceToolImpl() {
  const [list, setList] = useState(sample); const [shop, setShop] = useState('My Daily Price List');
  const [date, setDate] = useState(() => new Date().toLocaleDateString('en-CA'));
  const result = useMemo(()=>parsePriceList(list),[list]);
  const formattedDate = date ? new Date(`${date}T00:00:00`).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}) : '';
  return <><div className="app-intro"><h2>A beautiful price list in a few clicks</h2><p>Paste items, set your shop name, and print or save a clear daily price board.</p></div>
  <div className="app-grid"><section className="panel"><div className="panel-header"><h3>01 / Your price list</h3><span className="panel-hint">Item, Price, Unit</span></div><div className="field-row"><div className="field"><label htmlFor="shop-name">Business or list name</label><input id="shop-name" maxLength={80} value={shop} onChange={e=>setShop(e.target.value)}/></div><div className="field"><label htmlFor="price-date">Date</label><input id="price-date" type="date" value={date} onChange={e=>setDate(e.target.value)}/></div></div><div className="field"><label htmlFor="price-list-input">Products and prices (one per line)</label><textarea id="price-list-input" value={list} onChange={e=>setList(e.target.value)} placeholder={'Rice,65,kg\nWheat Flour,42,kg\nSoap,35,each'}/></div><div className="action-row"><button className="btn ghost" type="button" onClick={()=>setList(sample)}>Load sample</button><button className="btn ghost" type="button" onClick={()=>setList('')} disabled={!list}>Clear</button></div>{result.skipped.length>0&&<div className="notice warn" role="status">{result.skipped.length} line(s) could not be parsed. Use: Product Name, 65, kg. Unrecognized lines are excluded.</div>}</section>
    <section className="panel price-print-panel"><div className="panel-header"><h3>02 / Live preview</h3><span className="panel-hint">Ready to print</span></div><div className="price-sheet" aria-label="Printable price list" id="price-sheet"><div className="price-sheet-header"><div><h2>{shop.trim()||'Price List'}</h2><span>Fresh prices, clearly listed</span></div><span className="price-sheet-date">{formattedDate}</span></div><table><thead><tr><th>Item</th><th>Unit</th><th>Price</th></tr></thead><tbody>{result.items.map((row,i)=><tr key={i}><td>{row.item}</td><td>{row.unit}</td><td>₹{row.price.toLocaleString('en-IN',{maximumFractionDigits:2})}</td></tr>)}</tbody></table>{!result.items.length&&<p>No products yet. Add items to see your price list.</p>}<div className="price-sheet-footer">Made with Aetherexa Tools</div></div><p className="muted" style={{marginTop:15}}>{result.items.length} products · ₹ prices</p><div className="action-row"><button className="btn primary" type="button" disabled={!result.items.length} onClick={()=>window.print()}><Printer size={15}/> Print / Save PDF</button><button className="btn ghost" type="button" disabled={!result.items.length} onClick={()=>downloadText(result.csv,'aetherexa-price-list.csv')}><Download size={15}/> Export CSV</button></div><p className="muted">Use your browser’s Save as PDF printer to generate a PDF file.</p></section></div></>;
}
